version: "3.8"

x-adminer-volumes:
  &adminer-volumes
  - ./adminer.css:/var/www/html/adminer.css
  - ./plugins:/var/www/html/plugins/
  - ./server_list.json:/var/www/html/server_list.json

services:
  adminer-web:
    image: adminer:4.8.1
    volumes:
      *adminer-volumes
    environment:
      - VIRTUAL_HOST=adminer.local
      - VIRTUAL_PORT=8080
      - ADMINER_PLUGINS=login-servers tables-filter edit-foreign
    network_mode: "bridge"
    restart: always

